name: banking_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  flutter_neumorphic_plus: ^3.3.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  another_flushbar: ^1.12.30
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

# <-- NOTE: must use `flutter_icons` key (plugin looks for this)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/finpay_icon.png"
  adaptive_icon_background: "#00E1A0"      # optional: color or image_path
  adaptive_icon_foreground: "assets/icons/finpay_icon.png"

flutter_native_splash:
  color: "#2B4DFF"
  image: assets/images/finpay_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
